### ISSUE TITLE
run .nivsseq and .nivsstimprof

### ISSUE THREAD

**Issue by ihils** [ni/niveristand-python#20]
How to execute existing .nivsseq and .nivsstimprof via python?

**Comment by cheloizaguirre** [comment]
Currently we don't have that functionality available. However the legacy API can be used to run stimulus profiles. You can find the documentation here [https://niveristand-python.readthedocs.io/en/latest/api_reference/legacy.html#niveristand.legacy.NIVeriStand.Stimulus.RunStimulusProfile](https://niveristand-python.readthedocs.io/en/latest/api_reference/legacy.html#niveristand.legacy.NIVeriStand.Stimulus.RunStimulusProfile)
