### ISSUE TITLE
Make enum34 an optional dependency

### ISSUE THREAD

**Issue by iwane-pl** [ni/niveristand-python#22]
There is a dependency on `enum34` in this project. This package is relevant only for older Python versions - 3.4+ have enums built-in. The problem is that installing `enum34` can break other packages depending on `sys.path` order - in my case installing `enum34` on Python 3.6 breaks installation of PyInstaller. For more discussion, please see https://bitbucket.org/stoneleaf/enum34/issues/19/enum34-isnt-compatible-with-python-36 

Can `enum34` be made a conditional dependency in requirements? It is possible with current pip/setuptools versions to specify the requirement as follows: `enum34;python_version<"3.4"`.

**Comment by cheloizaguirre** [comment]
Fixed in latest release by #25
