### ISSUE TITLE
Calling an RT sequence within a sequence andd its subsequence causes an exception.

### ISSUE THREAD

**Issue by KilometersG** [ni/niveristand-python#23]
**Problem**: While defining two sequences (let's call them SeqA and SeqB) I place wait.nivsseq in both SeqA and SeqB. I then call SeqA from within SeqB. This will result in the following exception:
System.ArgumentException: This node is attached to another node; it must be removed before inserting it
Parameter name: child
If I comment out SeqA inside SeqB, or I comment out the wait.nivsseq in SeqB this exception does not occur.

I believe this all works if you do the same thing while defining a Real-Time Sequence in the Stimulus Profile editor. 

**Steps to Reproduce**
Run the following script:
`from niveristand import nivs_rt_sequence, NivsParam, realtimesequencetools
from niveristand.clientapi import DoubleValue,ChannelReference
from niveristand.library import wait, localhost_wait, seqtime, wait_until_settled

@ NivsParam('var1', DoubleValue(0), NivsParam.BY_REF)
@ nivs_rt_sequence
def function1(var1):
    wait(var1)

@NivsParam('var2', DoubleValue(0), NivsParam.BY_REF)
@nivs_rt_sequence
def function2(var2):
    wait(var2)
    function1(DoubleValue(1))

realtimesequencetools.save_py_as_rtseq(function2, r"C:\Users\Public\Documents\National Instruments\NI VeriStand 2019\Stimulus Profiles\Python Examples")`

**Comment by cheloizaguirre** [comment]
Fixed in latest release by #27
