### ISSUE TITLE
Query about API support for triggering logging specification of Veristand

### ISSUE THREAD

**Issue by Jowitt419** [ni/niveristand-python#45]
Is there any API support for triggering logging specification of Veristand in current package.(Just a trigger and a terminator, no need to configure the channel in python.)

Do u have any plan scheduled for developing this function?

Thx a lot~

**Comment by Jowitt419** [comment]
I found an API in legacy:
This is my partial src based on Engine Demo:

```
workspace = NIVeristand.Workspace2("localhost")
...
workspace.StartDataLogging(configuration_name = 'Logging Specification - Engine Demo', logInfo = 'Logging')
...
workspace.StopDataLogging(configuration_name = 'Logging Specification - Engine Demo')
```

But it went wrong, seemed to be a Pythonnet issue:
No method matches give arguments for StartDataLogging: (<class 'str'>, <class 'str'>)

Can someone help me? Thx a lot!

**Comment by CiprianAnton** [comment]
The second argument should not be string.
Can you try something like: 
```
workspace.StartDataLogging(configuration_name, NIVeriStand.CreateLogInfo())
```

**Comment by Jowitt419** [comment]
Thank you Ciprian~
For the example case: Engine Demo
there is a configured nivslspec called: Logging Specification - Engine Demo.nivslspec existed in project.
i just want to trigger it.
So i tried as:
`workspace.StartDataLogging(configuration_name = 'Logging Specification - Engine Demo', logInfo = NIVeriStand.CreateLogInfo())`

And it returns exception: error code 0xfffb4e3c
the fault code suggests −307652: Failed to open a connection to NI VeriStand.exe.

Thx a lot~

**Comment by CiprianAnton** [comment]
Hey, you also need to configure the logInfo.

I just tested the following code snipped and it worked:
```
log_info = NIVeriStand.CreateLogInfo()
log_info.file_path = r'D:\VeriStandLoging.tdms'
log_info.description = "Engine demo logging"
log_info.rate = 10
channels_paths_to_log = [
    "Aliases/EnginePower",
    "Aliases/ActualRPM"]
channels_to_log = [NIVeriStand.CreateLogChannel(path) for path in channels_paths_to_log]
NIVeriStand.SetLogInfoChannels(log_info, channels_to_log)

workspace.StartDataLogging(configuration_name = 'Logging Specification - Engine Demo', logInfo = log_info)
time.sleep(1)
workspace.SetSingleChannelValue("Aliases/EnginePower", 1)
time.sleep(5)
workspace.StopDataLogging(configuration_name = 'Logging Specification - Engine Demo')
```

**Comment by Jowitt419** [comment]
Thank you so much. You are better than any NI engineer in China.

**Comment by monicalicareti** [comment]
I second Jowitt419. Thank you so much for this! The niveristand Python API is not clear around this and I had so many failed tries to get it working until someone pointed me to this thread.
