### ISSUE TITLE
Pythonnet support for python 3.10 

### ISSUE THREAD

**Issue by rdecarreau** [ni/niveristand-python#46]
# Description

Installing niveristand with python 3.10 does not work because pythonnet is only supported in --pre.
https://github.com/pythonnet/pythonnet/issues/1600

# Environment

Python v3.10
Windows 10 64bit

# Steps to recreate

Create a venv and Activate it
pip install niveristand -or- python -m pip install niveristand

Result is pythonnet installation failure.

# Workaround

Manually install pythonnet using `pip install --pre pythonnet`
Then install niveristand

**Comment by papowerNI** [comment]
PR #54 added support for python 3.10
